### PR TITLE
Add guidelines for linking to pages and forms

### PR DESCRIPTION
**Pull request by jplhomer**
We don't want to link to specific pages or forms in the templates. Here's why, and here's how to avoid it.

### CODE REVIEW

**Comment by kjbrum** [comment]
Is there a reason our templates need to be portable between sites?

**Comment by jplhomer** [comment]
@kjbrum Good catch – they don't really need to be. Noted and updated.

I think they just need to be flexible in nature. Everything else in there look good?

**Comment by kjbrum** [comment]
@jplhomer, so say we need to link to a page, for example, the "Team" page. We need to add a field in the "Options Page" to select what that "Team" page is?

**Comment by jplhomer** [comment]
@kjbrum Yeah, that's what I was thinking.

**Comment by TonyTandeski** [comment]
:+1:

**Comment by JonnaBuse** [comment]
:+1: Agree, hard-coded numbers tend to be error-prone and not flexible.

**Pull request merged**
