### PR TITLE
Add PHP spacing guidelines

### PR DESCRIPTION
**Pull request by jplhomer**
Regarding function calls.

**NOTE**: May need to add more regarding other types of calls (`for` loops, etc).

### CODE REVIEW

**Comment by kjbrum** [comment]
Anyone opposed to just putting spaces around the function arguments all the time?

**Comment by TonyTandeski** [comment]
:+1: I'm not opposed.

**Comment by JonnaBuse** [comment]
:+1: Spaces are good, I'll always vote for readability.

**Comment by jplhomer** [comment]
Sorry @kjbrum - I merged before asking if we need to update the spaces guidelines about using them all the time. Do we need to adjust?

**Comment by kjbrum** [comment]
@jplhomer If everyone else is good with it, I have been using spaces for both cases the past few days. I like it.

**Pull request merged**
