### PR TITLE
Add single quote usage spec

### PR DESCRIPTION
**Pull request by jplhomer**
Prefer single quotes over double quotes.

### CODE REVIEW

**Comment by jplhomer** [comment]
Anyone have thoughts on this? 

Note that double quotes could be useful for [complex (curly) string parsing](http://php.net/manual/en/language.types.string.php#language.types.string.parsing.complex), but I never seem to remember to use that.

**Comment by kjbrum** [comment]
I use single quotes, unless double quotes are needed.

**Comment by TonyTandeski** [comment]
I'm in the single quote arena with @kjbrum.

**Comment by JonnaBuse** [comment]
I learned with double quotes but don't see single quotes as a big deal. Can go with the team on this one.

**Pull request merged**
